# GitHub Actions for cmpossl
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Siemens AG, 2021-2023

name: CI

on: push

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: |
          # would need access to azure.archive.ubuntu.com:
          # sudo apt-get update
          # sudo apt-get install -y >/dev/null libssl-dev build-essential # not needed
          make -f Makefile_v1
          make -f Makefile_v1 clean
          make -f Makefile_v1 build
          DESTDIR=tmp make -f Makefile_v1 install
          DESTDIR=tmp make -f Makefile_v1 uninstall

  cmake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cmake
        run: |
          cmake .
          cmake --build .
          cmake -DCMAKE_BUILD_TYPE=Release .
          make clean build
          DESTDIR=tmp make install
          DESTDIR=tmp make uninstall

  deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: deb
        run: |
          # needs access to azure.archive.ubuntu.com:
          sudo apt-get update
          sudo apt-get install -y >/dev/null debhelper devscripts
          make -f Makefile_v1 deb
